### ISSUE TITLE
house.levelConnMap

### ISSUE THREAD

**Issue by billhhh** [facebookresearch/MT-EQA#3]
Hello,

Thank you for sharing the code and great work.
When I tried to run your code `python shortest-path-gen/generate-conn-maps.py`, an error [https://github.com/facebookresearch/MT-EQA/blob/master/eqa_data/pyutils/house3d.py#L191](url) occurred said cannot find house.levelConnMap

So I changed it to
```
self.level_obs_map = 1 - (self.env.house.connMap if self.env.house.connMap is not None
                              else np.ones((500 + 1, 500 + 1), dtype=np.int32))
```

May I know is it the same meaning as yours?

Best

**Comment by billhhh** [comment]
And it consumes memory intensively when I tried to run
```
python shortest-path-gen/generate-conn-maps.py
```
I am using a machine with a 64GB memo, out of memory

**Comment by billhhh** [comment]
Or is it possible to share your generated data? Thank you!

**Comment by lichengunc** [comment]
connMap is the connected area in a house, so maybe you cannot use np.ones((501, 501)) to replace it. All ones would mean this house is empty with no furniture:-) The connMap will be used to compute shortest path, so yes please run "shortest-path-gen/generate-conn-maps.py" firstly. 

It does requires a lot of memory to compute the connMaps of all houses. Maybe you could chunk your data into several portions, and compute each of them separately or one by one. This could resolve the issue of too high memory demand.

**Comment by endernewton** [comment]
Thanks @lichengunc! closing this issue.

**Comment by billhhh** [comment]
Thank you so much!
